[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39

[testenv]
deps = pytest >= 3.0.0, <4
commands = pytest
passenv = PYTHONPATH
"""
